# The current version of Seanime (Do not change)
version = ''
 
[cache]
# The directory where cached data is stored
dir = '$SEANIME_DATA_DIR/cache'
# The directory where transcode video segments are stored
transcodedir = '$SEANIME_DATA_DIR/cache/transcode'
 
[database]
# The name of the database
name = 'seanime'
 
[logs]
# The directory where logs are stored
dir = '$SEANIME_DATA_DIR/logs'
 
[manga]
# The directory where manga chapters are downloaded
downloaddir = '$SEANIME_DATA_DIR/manga'
 
[offline]
# The directory where offline assets are downloaded
assetdir = '$SEANIME_DATA_DIR/offline/assets'
# The directory where the offline database is stored
dir = '$SEANIME_DATA_DIR/offline'
 
[server]
# The host to bind the server to
host = '0.0.0.0'
# Whether the server should run in offline mode
offline = false
# The port to bind the server to
port = 43211
# Whether SEANIME_WORKING_DIR should be the binary path (true) or the system's working directory (false)
usebinarypath = true
 
[web]
# The directory where custom web assets like background images are stored
assetdir = '$SEANIME_DATA_DIR/assets'